### ISSUE TITLE
Option to skip discarded tabs?

### ISSUE THREAD

**Issue by mxmilkb** [joshuacant/tst-wheel_and_double#21]
Thanks you very much for the extension as it stands! I use [Auto Tab Discard](https://addons.mozilla.org/en-GB/firefox/addon/auto-tab-discard) to automatically hibernate tabs I haven't used for a while. My request would be for an option to skip these discarded tabs on scrolling between tabs so that their pages don't start loading up and slowing my computer down. More on tabs.discard [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard).

**Comment by joshuacant** [comment]
This is an excellent idea, but I'm not sure I'll have the time to implement it in the immediate future. I will leave this request open and mark it as help wanted, maybe someone will add it in and submit a pull request.

**Comment by amandamana** [comment]
I use [Tab Unloader for Tree Style Tab](https://github.com/Lej77/tab-unloader-for-tree-style-tab) and also want the option to skip unloaded tabs. I see there's already an option skip collapsed tabs so perhaps some of that code could be reused.

**Comment by amandamana** [comment]
I coded this feature. I added a new flag: `
let skipDiscarded = true;
` at the top of **background.js**

It should be fairly quick and straightforward to add this flag to **options.html** and **options.js** and the _loadOptions_, _reloadOptions_, and _createOptions_ functions in **background.js** if you want this setting to be user configurable.

Here is a trimmed-down _handleScroll_ function:
```
async function handleScroll(aMessage) {
    //console.log(`scrolled ${aMessage.deltaY > 0 ? "down" : "up"}`);

    if (enableScrollWindow && aMessage.shiftKey) {
        return handleWindowScroll(aMessage)
    }
    
    let tstTabs = aMessage.tabs;
    let activeTabIndex = tstTabs.findIndex(tab => tab.active);
    let direction = aMessage.deltaY > 0 ? 1 : -1;
    direction = scrollingInverted ? -direction : direction;
    let id = findNextTab(tstTabs, direction, activeTabIndex);

    await browser.tabs.update(id, {active: true});
    return true;
}
```
I removed the `firefoxTabs` argument passed to the findTab functions. It was an empty array that wasn't used for anything. Rather than create more variations of the findTab functions, I rewrote them as a single function that also checks if a tab is discarded:
```
function findNextTab(tstTabs, direction, activeTabIndex) {
    let nextTabIndex = activeTabIndex;
    let cycleCount = 0;
    do {
        nextTabIndex = nextTabIndex + direction;
        if (nextTabIndex < 0) {
            if (skipCycling) break;
            cycleCount++;
            nextTabIndex = tstTabs.length;
        } else if (nextTabIndex === tstTabs.length) {
            if (skipCycling) break;
            cycleCount++;
            nextTabIndex = -1;
        } else if (skipCollapsed) {
            if (!tstTabs[nextTabIndex].states.includes('collapsed')) {
                if (skipDiscarded) {
                    if (!tstTabs[nextTabIndex].discarded) return tstTabs[nextTabIndex].id; //next tab is not collapsed and not discarded and will become active
                } else return tstTabs[nextTabIndex].id; //next tab is not collapsed and will become active
            }
        } else if (skipDiscarded) {
            if (!tstTabs[nextTabIndex].discarded) return tstTabs[nextTabIndex].id; //next tab is not discarded and will become active
        } else return tstTabs[nextTabIndex].id; //next tab will become active
    } while (cycleCount < 2); //prevent an infinite loop if something breaks; a tree with only collapsed or discarded tabs should be impossible
    return tstTabs[activeTabIndex].id; //exited the do loop because we are not cycling or have cycled more than once; the active tab remains the same
}
```
You can delete the _findNonCollapsedTab_ and _findAnyNextTab_ functions.

**Comment by joshuacant** [comment]
Excellent! Can you add the setting to the options (I think this should be up to the user, with a default of yes/on) and then send me a pull request?

**Comment by amandamana** [comment]
I assume a pull request is some sort of github feature, which I'd rather not spend the time learning how to use. I already spent more time than I should have figuring out the TST API and how to load and debug a temporary extension in Firefox.

If it's something that won't take me more than 30 minutes, can you provide a high-level walkthrough of what I'd need to do in order to send a pull request. The only thing I know how to do on github is comment on issues.

**Comment by joshuacant** [comment]
Yeah, it's a GitHub thing. There are loads of tutorials out there, but I'm not sure any of them will you get from 0 to Pull Request in 30 minutes or less.

Just zip up your working directory (the one you aim Firefox at to manually load the extension) upload it somewhere, and send me a link. I'll look at integrating the changes manually.

Just to calibrate your expectations, I might not have time to do this until next month at the earliest.
