### ISSUE TITLE
Allow to scroll the window tab

### ISSUE THREAD

**Issue by jreybert** [joshuacant/tst-wheel_and_double#5]
Hi, awesome to find this feature back, thanks for this addon².

I would like something that has not been in pre57 tree style tab: if I scroll, I want to move to previous/next tab, like your addon works today. But if scroll, pressing <kbd>Shift</kbd> or <kbd>Ctrl</kbd> (or something else, configurable), I want to move around in the tab window, in the case I have more tabs than it can fit in the window.

**Comment by joshuacant** [comment]
My first thought after reading the request is that it wouldn't be possible with the TST API as it is currently. But actually the TST API supports sending 'scroll' messages that should allow another addon to move the scroll position. So that half is possible.

I think the impossible part would be detecting the keyboard modifier. I'm not a WebExtensions expert, so I'm not the best person to say for sure if it's impossible or not. However, I don't know of a way for an addon to globally detect modifier key presses and releases.

I'll leave this request open, in case other people have better information than I, or want to submit code showing how it can be done.

**Comment by Sporif** [comment]
Well there is `aMessage.ctrlKey`,  `aMessage.shiftKey` and  `aMessage.altKey` that will tell you if those keys are pressed while scrolling.

**Comment by joshuacant** [comment]
The "help wanted" tag works! I think! @AllenAnthes submitted a pull request that I accepted and the feature works. I'll put out a new build soon, but we're also trying to squash the persistent "stops working sometimes" bug too.
