### ISSUE TITLE
Occasionally stops working after Firefox launch or update.

### ISSUE THREAD

**Issue by roman-sc** [joshuacant/tst-wheel_and_double#6]
For a few days now, scrolling just stops working suddenly. I am on 58.0b10 64bit right now.
Sometimes it stops after having browser open few hours/days. Sometimes scroll isnt working right after opening new firefox. In most cases its working.
I wasnt able to reproduce the problem reliably.
I tried updating the firefox version and tried to change to addon version from firefox website. Didnt help.

**Comment by joshuacant** [comment]
I'm not seeing this myself, so I'll probably need more information to figure out what's going on. I'm using (non-beta, non-dev, non-nightly) Firefox 57.0.1 64bit and whatever the latest AMO release version of Tree Style Tab is. I probably use Firefox something like 10 hours a day, and the only random stop I've had in the last few weeks was when TST updated and the two addons didn't sync back up. 

@roman-sc and @DeaD3R please provide more information, like what TST and TST-Wheel vesions, Firefox versions, OS, etc... Hopefully there's a clear pattern, because it's not something I'm seeing in my use.

**Comment by DeaD3R** [comment]
Currently on 57.0.2 64bit, TST 2.4.1 and 1.1.0 of this extension. Had this happen two, maybe three times total over the past few weeks. Disabling and enabling your extension fixes it. Maybe TST was updated in the background at those times, I didn't check. I'll keep an eye out if it happens again.

**Comment by joshuacant** [comment]
Not re-registering to TST after it updates is definitely a known issue, and something I need to look at, just haven't had the time. I'm using the code that Piro posted as the example for re-registering but I must be doing something wrong, because it's not working. I have my Firefox set to manual update addons, so I know exactly when TST updates and thus why scrolling stops working. Maybe if TST is background updating it just seems like scrolling dies for no reason.

Hopefully that's all this is, but @roman-sc said he'd had it not work right after freshly opening a new instance of Firefox, and that's something I have never seen. When my extension loads, it tries to connect to TST every 2 seconds on a loop until it finally does. I suppose there's a tiny possibility there's an issue with TST itself, but I doubt it, Piro is much more knowledgeable about this stuff than I am.

**Comment by DeaD3R** [comment]
Can confirm, TST just updated, the sidebar refreshed and this extension stopped working. That was probably why it stopped working for me before as well. Simple disable/enable fixes it though so it's not a big problem.

**Comment by roman-sc** [comment]
Sorry i was off for longer time.
My base TST addon is version 2.4.3.
Firefox is 58.0b10 (64-bit), i have retested the issue with latest 58.0b11 (64-bit). Both versions have the same problem.

When i open firefox in 10 different windows at a time, i can use scroll function only in (average) 5 windows. Scrolling restores in the broken firefox window after disabling/enabling TST mouse wheel and double click (v 1.1.0) addon.

When opening firefox one-by-one, there is about 50% chance that the scrolling will not work. In the window that has scrolling working, it stops in some amount of time. I wasnt able to keep scrolling functionality for longer time last few days/weeks. It was working correctly before that(on new (possibly a bit older) TST and in beta ffox).

I was going to change firefox update channel from beta to normal and i guess this will stop happening. I will let you know.

**Comment by joshuacant** [comment]
I don't think I ever had it not work right after opening Firefox, but ever since updating to the most recent TST I've seen it at least 4 times in the last few days. I need to find time to debug and play around. Before taking the issue upstream to Piro I want to make sure it's not something I'm doing wrong.

At any rate, this issue is definitely real (along with not re-activating after TST updates) so I will have to find some time to work on it.

**Comment by roman-sc** [comment]
I tried to switch to 57.0.2 (64-bit), but its still happening. I will try older TST versions and see if that helps. Thanks.

**Comment by Sporif** [comment]
Windows 10
TST 2.4.3
TST-Wheel 1.1.0
Both 57.0.2 and Nightly (2017-12-13)

I've found the scrolling stops working on every alternate restart. It also stops working when updating TST or disabling and then re-enabling TST. A disable and re-enable of TST-Wheel fixes the scrolling in every case.
 
I made a test version on Nightly with the registration timer removed and it now works on practically every start up. There's still the occasional failure though. All I did was:
```
line 21    //clearTimeout(registrationTimer);
```
and
```
line 86    //var registrationTimer = setInterval(registerToTST, 2000);
line 87    registerToTST();
```

But it still stopped working after updating TST or disabling and then re-enabling TST. So I made one more simple change. I switched from using `const ext_ID` to getting it from `browser.management.getSelf` :
 
````
line 13    async function registerToTST() {
line 14      var self = await browser.management.getSelf();  
line 15      var success = await browser.runtime.sendMessage(kTST_ID, {
line 16        type: 'register-self',
line 17        name: self.id,
````
And now it works through updates and disable/enables of TST. And it consistently works on every start up without fail. This is the same change I recommended to TST-MiddleClick to fix a similar [issue](https://github.com/AlexEndris/tst-middleclick/issues/1).

Then I tried it without the first edit, just the second, and it still worked properly. It seems the first edit by itself fixes the restart issues (mostly), but the second edit by itself fixes both the restart and update issues completely. Both edits combined give the same result of just the second edit.

So far TST-MiddleClick works perfectly after that change, so I think adding the second edit and removing the timer is the right way to go.

**Comment by joshuacant** [comment]
I did the timer to try to work around the problem mentioned in the TST API docs, about addons being loaded in the wrong order. I thought it was the fix I needed to "the not registering at startup" problem, which almost entirely went away after adding it. But, like I've said before, I'm no expert on this stuff, so lets give this a whirl. Thank you for taking the time to test out all the different version combinations as well as coming up with a solution. 

I wonder why using self.id as the name value should have this sort of effect? In that other addon, he was passing an empty string, but I changed the code sample provided by Piro to use a constant, since I knew I wasn't using any i18n stuff.

I'll give this a test myself for a few days before pushing it out as an update on AMO, and then we can see if it goes away for good or if it still pops up from time to time.

**Comment by joshuacant** [comment]
I just uploaded the signed test build with only these changes: https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.1.1

Try it out if you want to and let me know how it goes. Just keep in mind you may have to remove it and replace it with the AMO release in order to continue getting updates.

**Comment by Sporif** [comment]
Seems to be working fine. I'll test it out for a day or two to be sure.

**Comment by roman-sc** [comment]
I have been using 1.1.1 with 57.0.2 (64-bit) and TST 2.4.3. It just stopped working (after having firefox open for long time). It happened first time in days. I will keep an eye on it.

**Comment by joshuacant** [comment]
Same here. I've had one failure in the last 4 days. Certainly better, but obviously not 100% yet.

As soon as I find some time, I want to turn on a lot of debug statements and generate some logs to see if I can find a pattern to the behavior. However, I wonder what point will have to be good-enough, given my lack of expertise in the area of WebExtensions. Speaking for myself, scrolling tabs is such a vital part of my workflow, I don't mind having to disable/enable it once in a while. It's a small price to pay until someone can come along and do it better than I have.

**Comment by derhoch** [comment]
For me, the add-on does not work, when I launch Firefox. But, when I go to the add-on settings, and click "save options", it starts working immediatly. Maybe that helps to create a bugfix.

**Comment by joshuacant** [comment]
Hi everyone, I might have a fix for this. At the very least I have something I'd like more people to try out. I haven't pushed the code to github yet, but here's what it does:

1. A registrationStatus flag is set to false.
2. My addon attempts to register with TST, and if successful, sets the flag to true, the loop is escaped, and things continue normally.
3. If the flag remains false, 1 second is added to a timeout, and then the registration is attempted again.
4. This continues, adding one more second each time until the timeout reaches 10 seconds, then it gives up, however it will still react to a 'Ready' message from TST, in case it sends one out eventually.

If you're willing, snag the test release (AMO signed) from here: https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.2.1

Please report back with any discoveries, particularly if it goes for at least a week without any failed registrations at startup. If it blows up, you can remove this test version and install the release version from AMO, then tell me what happened.

If this does solve the problem, I'll probably adjust the number of attempts and the size of the timeout increases. I just went with 10 and 1 for simplicity's sake.

**Comment by joshuacant** [comment]
Alright, it's been just about 2 weeks. I haven't seen a single registration failure, even on my work PC which for some reason would fail roughly every other day. Has anyone seen any failures at all?

**Comment by DeaD3R** [comment]
Used to fail after almost every FF launch and had to disable/enable it. Now I haven't had a problem since I installed that test release. Thanks for fixing it, great work.

**Comment by joshuacant** [comment]
I submitted 1.3 to AMO and it should be live now. Looks like this issue is finally resolved. I had no issues with the 10 and 1 timeout values, so I just left them in place. I'll change them in the future if there are edge cases that crop up or something.
