### ISSUE TITLE
Working with FF version PRIOR to Firefox 57 ?

### ISSUE THREAD

**Issue by JohnDeZoom** [joshuacant/tst-wheel_and_double#9]
Hello, this is not really an error it's more of an enquiry.
I have Treestyle Tab installed on FFv56 andd I've just discovered your add-ons to TreestyleTab.
Now, my understanding was that Tree Style Tab, being uncompatible with FF from v57 on would not then work, so I've frozen at v56.
Now, when I found your 3 add-ons to TreeStyleTab on the FF Add-ons search page they are marked in RED and aren't downloadable with a click (don't worry I've figured out how to get them). It also says you need to install v57 for them to work !!!!!
My question is - why is TreestyleTab, and your extensions, working on v57 and after ?
and - do you really need to install FF 57 or after for your extensions to work or is it just a ruse by FF to get people to update (and then suddenly the add-ons won't work) ?
Thanks

**Comment by joshuacant** [comment]
Seems like you've been misinformed. Tree Style Tab works on v57, and has since shortly before Firefox 57 came out last November.

However, if you want wheel scrolling and reloading on versions prior to v57, install Tab Mix Plus. Ditto for the other functions in my other extensions. They're all part of TMP, which does not work with Firefox 57.
